FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY api-aspnet/*.csproj ./api-aspnet/
RUN dotnet restore ./api-aspnet/api-aspnet.csproj

COPY api-aspnet/. ./api-aspnet/
RUN dotnet publish ./api-aspnet/api-aspnet.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

# AWS load balancer handles HTTPS
ENV ASPNETCORE_URLS=http://0.0.0.0:8080

EXPOSE 8080
ENTRYPOINT ["dotnet", "api-aspnet.dll"]
